### ISSUE TITLE
19.2 execコマンドの例

### ISSUE THREAD

**Issue by chezou** [tatsu-zine/naruhounix#45]
3段落4行目の、一方、exec()みたいなの部分の中括弧の閉じる位置が間違っています。
また、シングルクォートの入れ子もできませんよね？
正しくは、`exec("ls * | awk '{print($1)}'")`等ではないでしょうか。

**Comment by Segilo** [comment]
v 1.1.4 ですが、19.3に残ってますね。

**Comment by snoozer05** [comment]
@Segilo ご指摘ありがとうございます！コードの誤りは修正していたのですが、組版上の問題が合わせて発生していたのを見落としておりました...(`}`が誤って解釈されてしまって表示がおかしくなってしまっておりました)。こちらについては次版にてあらためて修正いたします :bow:
