### ISSUE TITLE
“14.4　特定の子プロセスを待つ” 「Process.wait と Process.wait2 と同じだが」

### ISSUE THREAD

**Issue by ta1kt0me** [tatsu-zine/naruhounix#57]
v1.1.2です。

第２段落の

```
彼らがどんなことをするのかは、おおむね察しがつくんじゃないだろうか。ほとんど Process.wait と Process.wait2 と同じだが、終了を待つのは任意の子プロセスどれか1つではなく、指定した子プロセスになる。
```

に `Process.wait と Process.wait2 と同じだが、` とありますが、typoでしょうか。

**Comment by snoozer05** [comment]
ご指摘ありがとうございます！

原文が

> You can probably guess what these do. They function the same as Process.wait
and Process.wait2 except, rather than ...

となっていますので、一応 typo ではないつもりなのでした。前の文の 「`Process.waitpid` と `Process.waitpid2`」と形をあわせたためにこうなってしまったように記憶しています。

ただ、一文だけで見ると「〜と〜と」となっていて、たしかに読みにくい（一見 typoにも見えてしまう）ですね...

> ほとんど Process.wait と Process.wait2 と同じだが、
終了を待つのは任意の子プロセスどれか1つではなく、指定した子プロセスになる。

を

> ほとんどの動きは Process.wait や Process.wait2 と一緒だ。違いは、任意の子プロセスの終了を待つのではなく、指定した子プロセスの終了を待つという点になる。

とすると良いでしょうか...??

**Comment by ta1kt0me** [comment]
はい！読みやすい翻訳をありがとうございます:smiley:

**Comment by snoozer05** [comment]
ありがとうございます！それでは、こちらの内容で反映するようにいたします :-)
また何かありましたらよろしくお願いいたします！
