### ISSUE TITLE
11.1 fork(2) を使え、ルーク　の誤字？

### ISSUE THREAD

**Issue by a-know** [tatsu-zine/naruhounix#60]
v1.1.2です。

> 子プロセスは親プロセスのメモリにあるものをすべてのコピーする。

ここは、

* 子プロセスは親プロセスのメモリにあるものすべてをコピーする。
* 子プロセスは親プロセスのメモリにあるもののすべてをコピーする。

上記のいずれかが適切かと思いました :)

**Comment by snoozer05** [comment]
ありがとうございます！次バージョンにて修正いたします！
