### ISSUE TITLE
14.1 子守り　の文字重複

### ISSUE THREAD

**Issue by a-know** [tatsu-zine/naruhounix#61]
v1.1.2です。

> Ruby ではその方法の一つととして

「一つとして」の `と` が重複しているように思いました :)

**Comment by snoozer05** [comment]
ありがとうございます！次バージョンにて修正いたします！

**Comment by a-know** [comment]
ご確認ありがとうございます！
まだ本を読んでいる途中なので、またちょこちょこと報告させて頂くかもしれませんが、
よろしくお願いします 🙇

**Comment by snoozer05** [comment]
こちらこそ報告いただけてとても助かっています 😄ありがとうございます。
気になるところがありましたら、これからも気軽にフィードバックいただけるととても嬉しいです 🙏

**Comment by a-know** [comment]
@snoozer05 遅くなりましたが、本日全て読み終わりました！
すでに挙げさせていただいた issue 以外には、誤字脱字は見受けられませんでした！
素晴らしい本をありがとうございました！

**Comment by snoozer05** [comment]
@a-know 完走お疲れさまです！丁寧に読んでいただいて、とても嬉しかったです :-) ありがとうございました！
