### ISSUE TITLE
付録3 prefork サーバ - Rails アプリの読み込み 中の商品名について

### ISSUE THREAD

**Issue by ryunix** [tatsu-zine/naruhounix#63]
v1.1.2 です。

P.104 付録3 prefork サーバ - Rails アプリの読み込み に記載されている「Macbook」という商品名ですが、正しくは「MacBook」になるのかなと思いました。
細かい話ですが、気になってしまいましたのでご報告です。

**Comment by snoozer05** [comment]
ご報告ありがとうございます！そうですね。直します。
