### ISSUE TITLE
ソースコードのリンク切れ

### ISSUE THREAD

**Issue by takahashim** [tatsu-zine/naruhounix#69]
https://github.com/tatsu-zine/naruhounix/blob/master/README.md からリンクしている https://pragprog.com/titles/jsunix/source_code のページがリンク切れになっています。

こちらはzipファイルとしてダウンロードできる、ということで良いでしょうか？

**Comment by unasuke** [comment]
#72 を作成しました。落としてきたzipの中にspyglassが含まれてるのを確認しています。

![image](https://github.com/tatsu-zine/naruhounix/assets/4487291/b2b0a7db-7c68-4682-8d93-69f7cff2bb2d)

**Comment by takahashim** [comment]
こんなページが！　ありがとうございます！
